import { PrismaClient } from "../lib/generated/prisma/client"
import { PrismaLibSql } from "@prisma/adapter-libsql"

const dbUrl = process.env.DATABASE_URL ?? ("file:" + require("path").resolve(__dirname, "../dev.db"))
const adapter = new PrismaLibSql({ url: dbUrl })
const prisma = new PrismaClient({ adapter })

async function main() {
  // Track
  const ppl = await prisma.track.upsert({
    where: { slug: "ppl" },
    update: {},
    create: { slug: "ppl", name: "Private Pilot", shortName: "PPL", description: "Earn your Private Pilot Certificate.", icon: "✈️", sortOrder: 1 },
  })

  // Stub tracks
  for (const t of [
    { slug: "ir", name: "Instrument Rating", shortName: "IR", description: "Fly in the clouds legally and safely.", icon: "🌧️", sortOrder: 2 },
    { slug: "cpl", name: "Commercial Pilot", shortName: "CPL", description: "Get paid to fly.", icon: "💼", sortOrder: 3 },
    { slug: "me", name: "Multi-Engine Rating", shortName: "ME", description: "Master multi-engine aircraft.", icon: "🛩️", sortOrder: 4 },
    { slug: "cfi", name: "Flight Instructor", shortName: "CFI", description: "Teach the next generation of pilots.", icon: "👨‍🏫", sortOrder: 5 },
    { slug: "atp", name: "Airline Transport Pilot", shortName: "ATP", description: "The highest pilot certificate.", icon: "🛫", sortOrder: 6 },
  ]) {
    await prisma.track.upsert({ where: { slug: t.slug }, update: {}, create: t })
  }

  // Units
  const unit1 = await prisma.unit.upsert({
    where: { trackId_slug: { trackId: ppl.id, slug: "principles-of-flight" } },
    update: {},
    create: { trackId: ppl.id, slug: "principles-of-flight", title: "Principles of Flight", description: "The four forces and how wings generate lift.", icon: "🌬️", sortOrder: 1 },
  })

  const unit2 = await prisma.unit.upsert({
    where: { trackId_slug: { trackId: ppl.id, slug: "aircraft-systems" } },
    update: {},
    create: { trackId: ppl.id, slug: "aircraft-systems", title: "Aircraft Systems", description: "Engines, fuel, electrical, and flight controls.", icon: "⚙️", sortOrder: 2 },
  })

  // Lessons for unit1
  const l1 = await prisma.lesson.upsert({
    where: { unitId_slug: { unitId: unit1.id, slug: "four-forces" } },
    update: {},
    create: { unitId: unit1.id, slug: "four-forces", title: "Four Forces of Flight", description: "Lift, weight, thrust, and drag in equilibrium.", estimatedMins: 10, sortOrder: 1 },
  })
  const l2 = await prisma.lesson.upsert({
    where: { unitId_slug: { unitId: unit1.id, slug: "stalls" } },
    update: {},
    create: { unitId: unit1.id, slug: "stalls", title: "Stalls and Recovery", description: "What causes a stall and how to recover safely.", estimatedMins: 10, sortOrder: 2 },
  })

  // Sections for l1 — always refresh to pick up content changes
  await prisma.lessonSection.deleteMany({ where: { lessonId: l1.id } })
  await prisma.lessonSection.createMany({
    data: [
      {
        lessonId: l1.id,
        title: "The Four Forces",
        content: `Every aircraft in flight is acted on by four forces. In **straight-and-level unaccelerated flight**, these forces are perfectly balanced:

- **Lift** — acts upward, perpendicular to the flight path, generated by the wings
- **Weight** — acts downward through the aircraft's center of gravity
- **Thrust** — acts forward, produced by the engine and propeller
- **Drag** — acts rearward, opposing forward motion

When Lift = Weight and Thrust = Drag, the aircraft maintains constant altitude and speed.

[DIAGRAM:four-forces]

:::info
The four forces are always present in flight — even in a glide. When the engine is off, thrust disappears and drag eventually brings the aircraft to a stop (on the ground).
:::`,
        sortOrder: 1,
      },
      {
        lessonId: l1.id,
        title: "Generating Lift",
        content: `Lift is generated by the **angle of attack (AoA)** — the angle between the wing's chord line and the relative wind. As AoA increases, lift increases proportionally.

However, there is a limit. Beyond the **critical angle of attack** (typically 15–18°), airflow separates from the upper wing surface and lift drops dramatically. This is called a **stall**.

Drag the slider in the diagram below to see how lift changes with angle of attack:

[DIAGRAM:angle-of-attack]

:::warning
A stall can occur at **any airspeed and any attitude**. It is purely a function of exceeding the critical angle of attack — not of going too slow.
:::

:::tip
The stall speed listed in your POH (VS0, VS1) assumes a specific bank angle and weight. In a steep turn, stall speed increases significantly.
:::`,
        sortOrder: 2,
      },
    ],
  })

  // Sections for l2
  await prisma.lessonSection.deleteMany({ where: { lessonId: l2.id } })
  await prisma.lessonSection.createMany({
    data: [
      {
        lessonId: l2.id,
        title: "What Is a Stall?",
        content: `A **stall** is an aerodynamic condition, not an airspeed condition. It occurs the moment the wing exceeds its critical angle of attack — typically around 15–18° depending on the airfoil.

At this point, smooth **laminar airflow** over the upper wing surface breaks down into turbulent separated flow. The wing can no longer generate enough lift to support the aircraft's weight.

:::warning
The #1 misconception: stalls happen when you "run out of airspeed." **Wrong.** You can stall at full throttle, in a dive, or while maneuvering at high speed. AoA is the only factor that matters.
:::`,
        sortOrder: 1,
      },
      {
        lessonId: l2.id,
        title: "Stall Recovery",
        content: `The standard stall recovery procedure is three steps, executed promptly:

1. **Reduce angle of attack** — apply forward pressure on the yoke/stick to lower the nose and un-stall the wings
2. **Apply full power** — maximize thrust to minimize altitude loss
3. **Level the wings** — use coordinated rudder to stop any rolling tendency

:::tip
The FAA recommends the mnemonic **"Pitch, Power, Rudder"** — though in practice, all three happen nearly simultaneously.
:::

Altitude loss during recovery varies. A clean stall at altitude may cost only 50–100 feet. An accelerated or departure stall can be far more dramatic. **Prompt recognition and recovery are critical.**`,
        sortOrder: 2,
      },
    ],
  })

  // Lessons for unit2
  const l3 = await prisma.lesson.upsert({
    where: { unitId_slug: { unitId: unit2.id, slug: "engines" } },
    update: {},
    create: { unitId: unit2.id, slug: "engines", title: "Reciprocating Engines", description: "How piston aircraft engines work.", estimatedMins: 10, sortOrder: 1 },
  })
  const l4 = await prisma.lesson.upsert({
    where: { unitId_slug: { unitId: unit2.id, slug: "fuel-systems" } },
    update: {},
    create: { unitId: unit2.id, slug: "fuel-systems", title: "Fuel Systems", description: "Fuel types, sumping, and fuel management.", estimatedMins: 8, sortOrder: 2 },
  })

  // Sections for l3
  await prisma.lessonSection.deleteMany({ where: { lessonId: l3.id } })
  await prisma.lessonSection.createMany({
    data: [
      {
        lessonId: l3.id,
        title: "The Four-Stroke Cycle",
        content: `Most training aircraft use a **horizontally-opposed, four-stroke, spark-ignition piston engine**. The engine produces power by burning a fuel/air mixture in cylinders. Each cylinder completes four distinct strokes per power cycle:

1. **Intake** — piston moves down, intake valve opens, fuel/air mixture is drawn in
2. **Compression** — both valves close, piston moves up, mixture compressed to ~1/8 volume
3. **Power** — spark plug fires, burning mixture expands and drives piston down — this is the only stroke that produces power
4. **Exhaust** — exhaust valve opens, piston moves up, burned gases pushed out

Step through the cycle using the interactive diagram:

[DIAGRAM:four-stroke]

:::info
Most training aircraft (like the Cessna 172) use a **four-cylinder, 160 hp Lycoming O-320** or similar. The firing order alternates cylinders to keep the crankshaft rotating smoothly.
:::`,
        sortOrder: 1,
      },
      {
        lessonId: l3.id,
        title: "Mixture Control",
        content: `The **mixture control** (red knob in most aircraft) adjusts the fuel/air ratio delivered to the engine.

At sea level, the fuel/air mixture is calibrated for maximum efficiency. As you climb, **air density decreases** but the fuel metering system delivers the same volume of fuel — making the mixture progressively **too rich** (excess fuel).

A rich mixture causes:
- Reduced engine efficiency
- Fouled spark plugs
- Increased fuel consumption

**Lean above 3,000 ft density altitude** to restore the correct ratio. The proper lean point is typically found by slowly pulling the mixture knob toward lean until engine RPM peaks, then enriching slightly.

:::warning
**Never lean below 75% power** or during takeoff and landing. A too-lean mixture at high power settings can cause engine damage from detonation.
:::`,
        sortOrder: 2,
      },
    ],
  })

  // Sections for l4
  await prisma.lessonSection.deleteMany({ where: { lessonId: l4.id } })
  await prisma.lessonSection.createMany({
    data: [
      {
        lessonId: l4.id,
        title: "Aviation Fuel Types",
        content: `General aviation aircraft use **aviation gasoline (Avgas)** — not automotive fuel. The grades are:

| Grade | Color | Use |
|-------|-------|-----|
| **100LL** | Blue | Most piston aircraft — "LL" = Low Lead |
| **100** (100/130) | Green | Older high-compression engines |
| **Jet-A** | Clear/straw | Turbine/jet engines only |

:::warning
**Misfueling is fatal.** Jet-A in a piston engine will cause engine failure. 100LL in a jet turbine will destroy it. Always verify fuel type before adding to the tanks.
:::

:::tip
The blue color of 100LL is a safety feature — it makes misfueling with Jet-A (clear) visually obvious during preflight.
:::`,
        sortOrder: 1,
      },
      {
        lessonId: l4.id,
        title: "Preflight Fuel Inspection",
        content: `Water contamination in aviation fuel is a leading cause of engine failure. Water is heavier than avgas and **sinks to the lowest point** in the tank and fuel system.

**Sumping procedure (required before every flight):**

1. Use the fuel sump tool (clear cylinder with a button valve)
2. Sample from each **wing tank sump**, the **gascolator/strainer**, and any other low points
3. Check for:
   - **Water** — appears as a separate clear layer at the bottom, or as bubbles
   - **Contamination** — dirt, debris, discoloration
   - **Correct color** — should be blue (100LL)
4. Discard contaminated samples away from the aircraft

:::info
If you find water, sump repeatedly until it's gone. Water often settles from condensation overnight — always sump after the aircraft has been parked for an extended period.
:::`,
        sortOrder: 2,
      },
    ],
  })

  // Questions for unit1
  const existingQ1 = await prisma.question.count({ where: { unitId: unit1.id } })
  if (existingQ1 === 0) {
    const q1 = await prisma.question.create({ data: { unitId: unit1.id, question: "A stall occurs when:", explanation: "A stall always occurs at the critical angle of attack, regardless of airspeed or aircraft attitude. It is an aerodynamic condition, not an airspeed condition.", farAimRef: "FAA-H-8083-25B Ch.4", difficulty: "easy" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q1.id, text: "The wing exceeds its critical angle of attack", isCorrect: true, sortOrder: 1 },
      { questionId: q1.id, text: "Airspeed drops below VS0", isCorrect: false, sortOrder: 2 },
      { questionId: q1.id, text: "The throttle is reduced to idle", isCorrect: false, sortOrder: 3 },
      { questionId: q1.id, text: "The aircraft is in a nose-high attitude", isCorrect: false, sortOrder: 4 },
    ]})

    const q2 = await prisma.question.create({ data: { unitId: unit1.id, question: "In straight-and-level unaccelerated flight, which statement is true?", explanation: "In unaccelerated (constant velocity) flight, all four forces are in equilibrium: lift equals weight, and thrust equals drag.", farAimRef: "FAA-H-8083-25B Ch.4", difficulty: "easy" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q2.id, text: "Lift equals weight and thrust equals drag", isCorrect: true, sortOrder: 1 },
      { questionId: q2.id, text: "Lift exceeds weight and thrust exceeds drag", isCorrect: false, sortOrder: 2 },
      { questionId: q2.id, text: "Thrust exceeds drag and lift equals weight", isCorrect: false, sortOrder: 3 },
      { questionId: q2.id, text: "Drag exceeds thrust and lift equals weight", isCorrect: false, sortOrder: 4 },
    ]})

    const q3 = await prisma.question.create({ data: { unitId: unit1.id, question: "What is the correct stall recovery procedure?", explanation: "Stall recovery requires reducing angle of attack (forward pressure), applying full power, and leveling the wings with coordinated rudder to minimize altitude loss.", difficulty: "medium" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q3.id, text: "Reduce AoA, full power, level wings with rudder", isCorrect: true, sortOrder: 1 },
      { questionId: q3.id, text: "Apply back pressure and add power", isCorrect: false, sortOrder: 2 },
      { questionId: q3.id, text: "Reduce power and lower the nose sharply", isCorrect: false, sortOrder: 3 },
      { questionId: q3.id, text: "Apply aileron in the direction of the stall", isCorrect: false, sortOrder: 4 },
    ]})
  }

  // Questions for unit2
  const existingQ2 = await prisma.question.count({ where: { unitId: unit2.id } })
  if (existingQ2 === 0) {
    const q4 = await prisma.question.create({ data: { unitId: unit2.id, question: "Most training aircraft use which grade of aviation fuel?", explanation: "100LL (low-lead) avgas is the most common fuel for piston aircraft. It is dyed blue for easy identification.", difficulty: "easy" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q4.id, text: "100LL (low-lead), dyed blue", isCorrect: true, sortOrder: 1 },
      { questionId: q4.id, text: "80/87, dyed red", isCorrect: false, sortOrder: 2 },
      { questionId: q4.id, text: "Jet-A, dyed clear", isCorrect: false, sortOrder: 3 },
      { questionId: q4.id, text: "100LL, dyed green", isCorrect: false, sortOrder: 4 },
    ]})

    const q5 = await prisma.question.create({ data: { unitId: unit2.id, question: "Why should you lean the mixture at higher altitudes?", explanation: "As altitude increases, air density decreases, making the mixture too rich. Leaning restores the proper fuel/air ratio, improving engine efficiency and preventing fouled spark plugs.", difficulty: "medium" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q5.id, text: "Air density decreases, making the mixture too rich", isCorrect: true, sortOrder: 1 },
      { questionId: q5.id, text: "Fuel pressure increases at altitude", isCorrect: false, sortOrder: 2 },
      { questionId: q5.id, text: "The carburetor enriches automatically", isCorrect: false, sortOrder: 3 },
      { questionId: q5.id, text: "To reduce fuel flow for longer range only", isCorrect: false, sortOrder: 4 },
    ]})

    const q6 = await prisma.question.create({ data: { unitId: unit2.id, question: "During preflight, fuel sumped from the tanks appears clear with no bubbles. This indicates:", explanation: "Clear, bubble-free avgas is correct. Blue color confirms 100LL. Water contamination appears as a separate clear layer at the bottom or as bubbles.", difficulty: "easy" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q6.id, text: "Water contamination is present", isCorrect: false, sortOrder: 1 },
      { questionId: q6.id, text: "The fuel is 100LL and uncontaminated", isCorrect: true, sortOrder: 2 },
      { questionId: q6.id, text: "The fuel tank is empty", isCorrect: false, sortOrder: 3 },
      { questionId: q6.id, text: "Jet-A has been inadvertently added", isCorrect: false, sortOrder: 4 },
    ]})
  }

  // Achievements
  const achievements = [
    { slug: "first-lesson", name: "First Flight", description: "Complete your first lesson.", icon: "🎯", xpReward: 50, category: "milestones" },
    { slug: "perfect-quiz", name: "Ace Pilot", description: "Score 100% on any quiz.", icon: "💯", xpReward: 100, category: "quizzes" },
    { slug: "7-day-streak", name: "Week Warrior", description: "Maintain a 7-day study streak.", icon: "🔥", xpReward: 75, category: "streaks" },
    { slug: "gold-mastery", name: "Gold Standard", description: "Earn gold mastery on a unit quiz.", icon: "🥇", xpReward: 150, category: "quizzes" },
    { slug: "ppl-complete", name: "Private Pilot", description: "Complete the entire PPL track.", icon: "🎓", xpReward: 500, category: "certifications" },
  ]
  for (const a of achievements) {
    await prisma.achievement.upsert({ where: { slug: a.slug }, update: {}, create: a })
  }

  console.log("Seed complete.")
}

main().catch(console.error).finally(() => prisma.$disconnect())
