import { PrismaClient } from "../lib/generated/prisma/client"
import { PrismaLibSql } from "@prisma/adapter-libsql"

const dbUrl = process.env.DATABASE_URL ?? ("file:" + require("path").resolve(__dirname, "../dev.db"))
const adapter = new PrismaLibSql({ url: dbUrl })
const prisma = new PrismaClient({ adapter })

async function main() {
  // Track
  const ppl = await prisma.track.upsert({
    where: { slug: "ppl" },
    update: {},
    create: { slug: "ppl", name: "Private Pilot", shortName: "PPL", description: "Earn your Private Pilot Certificate.", icon: "✈️", sortOrder: 1 },
  })

  // Stub tracks
  for (const t of [
    { slug: "ir", name: "Instrument Rating", shortName: "IR", description: "Fly in the clouds legally and safely.", icon: "🌧️", sortOrder: 2 },
    { slug: "cpl", name: "Commercial Pilot", shortName: "CPL", description: "Get paid to fly.", icon: "💼", sortOrder: 3 },
    { slug: "me", name: "Multi-Engine Rating", shortName: "ME", description: "Master multi-engine aircraft.", icon: "🛩️", sortOrder: 4 },
    { slug: "cfi", name: "Flight Instructor", shortName: "CFI", description: "Teach the next generation of pilots.", icon: "👨‍🏫", sortOrder: 5 },
    { slug: "atp", name: "Airline Transport Pilot", shortName: "ATP", description: "The highest pilot certificate.", icon: "🛫", sortOrder: 6 },
  ]) {
    await prisma.track.upsert({ where: { slug: t.slug }, update: {}, create: t })
  }

  // Units
  const unit1 = await prisma.unit.upsert({
    where: { trackId_slug: { trackId: ppl.id, slug: "principles-of-flight" } },
    update: {},
    create: { trackId: ppl.id, slug: "principles-of-flight", title: "Principles of Flight", description: "The four forces and how wings generate lift.", icon: "🌬️", sortOrder: 1 },
  })

  const unit2 = await prisma.unit.upsert({
    where: { trackId_slug: { trackId: ppl.id, slug: "aircraft-systems" } },
    update: {},
    create: { trackId: ppl.id, slug: "aircraft-systems", title: "Aircraft Systems", description: "Engines, fuel, electrical, and flight controls.", icon: "⚙️", sortOrder: 2 },
  })

  // Lessons for unit1
  const l1 = await prisma.lesson.upsert({
    where: { unitId_slug: { unitId: unit1.id, slug: "four-forces" } },
    update: {},
    create: { unitId: unit1.id, slug: "four-forces", title: "Four Forces of Flight", description: "Lift, weight, thrust, and drag in equilibrium.", estimatedMins: 10, sortOrder: 1 },
  })
  const l2 = await prisma.lesson.upsert({
    where: { unitId_slug: { unitId: unit1.id, slug: "stalls" } },
    update: {},
    create: { unitId: unit1.id, slug: "stalls", title: "Stalls and Recovery", description: "What causes a stall and how to recover safely.", estimatedMins: 10, sortOrder: 2 },
  })

  // Sections for l1
  const existingSections1 = await prisma.lessonSection.count({ where: { lessonId: l1.id } })
  if (existingSections1 === 0) {
    await prisma.lessonSection.createMany({ data: [
      { lessonId: l1.id, title: "The Four Forces", content: "**Lift** acts upward, **weight** downward, **thrust** forward, and **drag** rearward. In straight-and-level flight, lift equals weight and thrust equals drag.", sortOrder: 1 },
      { lessonId: l1.id, title: "Generating Lift", content: "Lift is generated by airflow over the wing. As angle of attack increases, lift increases — up to the critical angle of attack (~15–18°), beyond which the wing stalls.", sortOrder: 2 },
    ]})
  }

  // Sections for l2
  const existingSections2 = await prisma.lessonSection.count({ where: { lessonId: l2.id } })
  if (existingSections2 === 0) {
    await prisma.lessonSection.createMany({ data: [
      { lessonId: l2.id, title: "What Is a Stall?", content: "A stall occurs when the wing exceeds its **critical angle of attack**, not when airspeed drops below a specific value. Any airspeed, any attitude.", sortOrder: 1 },
      { lessonId: l2.id, title: "Stall Recovery", content: "Recovery: reduce angle of attack (push forward), add full power, level wings with rudder. Altitude loss varies — minimize it with prompt, correct action.", sortOrder: 2 },
    ]})
  }

  // Lessons for unit2
  const l3 = await prisma.lesson.upsert({
    where: { unitId_slug: { unitId: unit2.id, slug: "engines" } },
    update: {},
    create: { unitId: unit2.id, slug: "engines", title: "Reciprocating Engines", description: "How piston aircraft engines work.", estimatedMins: 10, sortOrder: 1 },
  })
  const l4 = await prisma.lesson.upsert({
    where: { unitId_slug: { unitId: unit2.id, slug: "fuel-systems" } },
    update: {},
    create: { unitId: unit2.id, slug: "fuel-systems", title: "Fuel Systems", description: "Fuel types, sumping, and fuel management.", estimatedMins: 8, sortOrder: 2 },
  })

  const existingSections3 = await prisma.lessonSection.count({ where: { lessonId: l3.id } })
  if (existingSections3 === 0) {
    await prisma.lessonSection.createMany({ data: [
      { lessonId: l3.id, title: "Four-Stroke Cycle", content: "**Intake → Compression → Power → Exhaust**. The mixture is ignited near top dead center; expanding gases push the piston down, rotating the crankshaft.", sortOrder: 1 },
      { lessonId: l3.id, title: "Mixture Control", content: "At altitude, air density decreases so the fuel/air mixture becomes rich. **Lean the mixture** above 3,000 ft density altitude to restore proper ratio and prevent fouled plugs.", sortOrder: 2 },
    ]})
  }

  const existingSections4 = await prisma.lessonSection.count({ where: { lessonId: l4.id } })
  if (existingSections4 === 0) {
    await prisma.lessonSection.createMany({ data: [
      { lessonId: l4.id, title: "Avgas Grades", content: "Most training aircraft use **100LL** (low-lead) avgas, dyed blue. Never use automotive fuel unless the aircraft has an STC authorizing it.", sortOrder: 1 },
      { lessonId: l4.id, title: "Preflight Fuel Check", content: "**Sump the tanks and strainer** before every flight. Water is heavier than avgas and sinks to the bottom. Clear, blue fuel with no water is required for safe flight.", sortOrder: 2 },
    ]})
  }

  // Questions for unit1
  const existingQ1 = await prisma.question.count({ where: { unitId: unit1.id } })
  if (existingQ1 === 0) {
    const q1 = await prisma.question.create({ data: { unitId: unit1.id, question: "A stall occurs when:", explanation: "A stall always occurs at the critical angle of attack, regardless of airspeed or aircraft attitude. It is an aerodynamic condition, not an airspeed condition.", farAimRef: "FAA-H-8083-25B Ch.4", difficulty: "easy" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q1.id, text: "The wing exceeds its critical angle of attack", isCorrect: true, sortOrder: 1 },
      { questionId: q1.id, text: "Airspeed drops below VS0", isCorrect: false, sortOrder: 2 },
      { questionId: q1.id, text: "The throttle is reduced to idle", isCorrect: false, sortOrder: 3 },
      { questionId: q1.id, text: "The aircraft is in a nose-high attitude", isCorrect: false, sortOrder: 4 },
    ]})

    const q2 = await prisma.question.create({ data: { unitId: unit1.id, question: "In straight-and-level unaccelerated flight, which statement is true?", explanation: "In unaccelerated (constant velocity) flight, all four forces are in equilibrium: lift equals weight, and thrust equals drag.", farAimRef: "FAA-H-8083-25B Ch.4", difficulty: "easy" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q2.id, text: "Lift equals weight and thrust equals drag", isCorrect: true, sortOrder: 1 },
      { questionId: q2.id, text: "Lift exceeds weight and thrust exceeds drag", isCorrect: false, sortOrder: 2 },
      { questionId: q2.id, text: "Thrust exceeds drag and lift equals weight", isCorrect: false, sortOrder: 3 },
      { questionId: q2.id, text: "Drag exceeds thrust and lift equals weight", isCorrect: false, sortOrder: 4 },
    ]})

    const q3 = await prisma.question.create({ data: { unitId: unit1.id, question: "What is the correct stall recovery procedure?", explanation: "Stall recovery requires reducing angle of attack (forward pressure), applying full power, and leveling the wings with coordinated rudder to minimize altitude loss.", difficulty: "medium" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q3.id, text: "Reduce AoA, full power, level wings with rudder", isCorrect: true, sortOrder: 1 },
      { questionId: q3.id, text: "Apply back pressure and add power", isCorrect: false, sortOrder: 2 },
      { questionId: q3.id, text: "Reduce power and lower the nose sharply", isCorrect: false, sortOrder: 3 },
      { questionId: q3.id, text: "Apply aileron in the direction of the stall", isCorrect: false, sortOrder: 4 },
    ]})
  }

  // Questions for unit2
  const existingQ2 = await prisma.question.count({ where: { unitId: unit2.id } })
  if (existingQ2 === 0) {
    const q4 = await prisma.question.create({ data: { unitId: unit2.id, question: "Most training aircraft use which grade of aviation fuel?", explanation: "100LL (low-lead) avgas is the most common fuel for piston aircraft. It is dyed blue for easy identification.", difficulty: "easy" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q4.id, text: "100LL (low-lead), dyed blue", isCorrect: true, sortOrder: 1 },
      { questionId: q4.id, text: "80/87, dyed red", isCorrect: false, sortOrder: 2 },
      { questionId: q4.id, text: "Jet-A, dyed clear", isCorrect: false, sortOrder: 3 },
      { questionId: q4.id, text: "100LL, dyed green", isCorrect: false, sortOrder: 4 },
    ]})

    const q5 = await prisma.question.create({ data: { unitId: unit2.id, question: "Why should you lean the mixture at higher altitudes?", explanation: "As altitude increases, air density decreases, making the mixture too rich. Leaning restores the proper fuel/air ratio, improving engine efficiency and preventing fouled spark plugs.", difficulty: "medium" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q5.id, text: "Air density decreases, making the mixture too rich", isCorrect: true, sortOrder: 1 },
      { questionId: q5.id, text: "Fuel pressure increases at altitude", isCorrect: false, sortOrder: 2 },
      { questionId: q5.id, text: "The carburetor enriches automatically", isCorrect: false, sortOrder: 3 },
      { questionId: q5.id, text: "To reduce fuel flow for longer range only", isCorrect: false, sortOrder: 4 },
    ]})

    const q6 = await prisma.question.create({ data: { unitId: unit2.id, question: "During preflight, fuel sumped from the tanks appears clear with no bubbles. This indicates:", explanation: "Clear, bubble-free avgas is correct. Blue color confirms 100LL. Water contamination appears as a separate clear layer at the bottom or as bubbles.", difficulty: "easy" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q6.id, text: "Water contamination is present", isCorrect: false, sortOrder: 1 },
      { questionId: q6.id, text: "The fuel is 100LL and uncontaminated", isCorrect: true, sortOrder: 2 },
      { questionId: q6.id, text: "The fuel tank is empty", isCorrect: false, sortOrder: 3 },
      { questionId: q6.id, text: "Jet-A has been inadvertently added", isCorrect: false, sortOrder: 4 },
    ]})
  }

  // Achievements
  const achievements = [
    { slug: "first-lesson", name: "First Flight", description: "Complete your first lesson.", icon: "🎯", xpReward: 50, category: "milestones" },
    { slug: "perfect-quiz", name: "Ace Pilot", description: "Score 100% on any quiz.", icon: "💯", xpReward: 100, category: "quizzes" },
    { slug: "7-day-streak", name: "Week Warrior", description: "Maintain a 7-day study streak.", icon: "🔥", xpReward: 75, category: "streaks" },
    { slug: "gold-mastery", name: "Gold Standard", description: "Earn gold mastery on a unit quiz.", icon: "🥇", xpReward: 150, category: "quizzes" },
    { slug: "ppl-complete", name: "Private Pilot", description: "Complete the entire PPL track.", icon: "🎓", xpReward: 500, category: "certifications" },
  ]
  for (const a of achievements) {
    await prisma.achievement.upsert({ where: { slug: a.slug }, update: {}, create: a })
  }

  console.log("Seed complete.")
}

main().catch(console.error).finally(() => prisma.$disconnect())
