import { PrismaClient } from "../lib/generated/prisma/client"
import { PrismaLibSql } from "@prisma/adapter-libsql"

const dbUrl = process.env.DATABASE_URL ?? ("file:" + require("path").resolve(__dirname, "../dev.db"))
const adapter = new PrismaLibSql({ url: dbUrl })
const prisma = new PrismaClient({ adapter })

async function main() {
  // Track
  const ppl = await prisma.track.upsert({
    where: { slug: "ppl" },
    update: {},
    create: { slug: "ppl", name: "Private Pilot", shortName: "PPL", description: "Earn your Private Pilot Certificate.", icon: "✈️", sortOrder: 1 },
  })

  // Stub tracks
  for (const t of [
    { slug: "ir", name: "Instrument Rating", shortName: "IR", description: "Fly in the clouds legally and safely.", icon: "🌧️", sortOrder: 2 },
    { slug: "cpl", name: "Commercial Pilot", shortName: "CPL", description: "Get paid to fly.", icon: "💼", sortOrder: 3 },
    { slug: "me", name: "Multi-Engine Rating", shortName: "ME", description: "Master multi-engine aircraft.", icon: "🛩️", sortOrder: 4 },
    { slug: "cfi", name: "Flight Instructor", shortName: "CFI", description: "Teach the next generation of pilots.", icon: "👨‍🏫", sortOrder: 5 },
    { slug: "atp", name: "Airline Transport Pilot", shortName: "ATP", description: "The highest pilot certificate.", icon: "🛫", sortOrder: 6 },
  ]) {
    await prisma.track.upsert({ where: { slug: t.slug }, update: {}, create: t })
  }

  // Units
  const unit1 = await prisma.unit.upsert({
    where: { trackId_slug: { trackId: ppl.id, slug: "principles-of-flight" } },
    update: {},
    create: { trackId: ppl.id, slug: "principles-of-flight", title: "Principles of Flight", description: "The four forces and how wings generate lift.", icon: "🌬️", sortOrder: 1 },
  })

  const unit2 = await prisma.unit.upsert({
    where: { trackId_slug: { trackId: ppl.id, slug: "aircraft-systems" } },
    update: {},
    create: { trackId: ppl.id, slug: "aircraft-systems", title: "Aircraft Systems", description: "Engines, fuel, electrical, and flight controls.", icon: "⚙️", sortOrder: 2 },
  })

  // Lessons for unit1
  const l1 = await prisma.lesson.upsert({
    where: { unitId_slug: { unitId: unit1.id, slug: "four-forces" } },
    update: {},
    create: { unitId: unit1.id, slug: "four-forces", title: "Four Forces of Flight", description: "Lift, weight, thrust, and drag in equilibrium.", estimatedMins: 10, sortOrder: 1 },
  })
  const l2 = await prisma.lesson.upsert({
    where: { unitId_slug: { unitId: unit1.id, slug: "stalls" } },
    update: {},
    create: { unitId: unit1.id, slug: "stalls", title: "Stalls and Recovery", description: "What causes a stall and how to recover safely.", estimatedMins: 10, sortOrder: 2 },
  })

  // Sections for l1 — always refresh to pick up content changes
  await prisma.lessonSection.deleteMany({ where: { lessonId: l1.id } })
  await prisma.lessonSection.createMany({
    data: [
      {
        lessonId: l1.id,
        title: "The Four Forces",
        content: `Every aircraft in flight is acted on by four forces. In **straight-and-level unaccelerated flight**, these forces are perfectly balanced:

- **Lift** — acts upward, perpendicular to the flight path, generated by the wings
- **Weight** — acts downward through the aircraft's center of gravity
- **Thrust** — acts forward, produced by the engine and propeller
- **Drag** — acts rearward, opposing forward motion

When Lift = Weight and Thrust = Drag, the aircraft maintains constant altitude and speed.

[DIAGRAM:four-forces]

:::info
The four forces are always present in flight — even in a glide. When the engine is off, thrust disappears and drag eventually brings the aircraft to a stop (on the ground).
:::`,
        sortOrder: 1,
      },
      {
        lessonId: l1.id,
        title: "Generating Lift",
        content: `Lift is generated by the **angle of attack (AoA)** — the angle between the wing's chord line and the relative wind. As AoA increases, lift increases proportionally.

However, there is a limit. Beyond the **critical angle of attack** (typically 15–18°), airflow separates from the upper wing surface and lift drops dramatically. This is called a **stall**.

Drag the slider in the diagram below to see how lift changes with angle of attack:

[DIAGRAM:angle-of-attack]

:::warning
A stall can occur at **any airspeed and any attitude**. It is purely a function of exceeding the critical angle of attack — not of going too slow.
:::

:::tip
The stall speed listed in your POH (VS0, VS1) assumes a specific bank angle and weight. In a steep turn, stall speed increases significantly.
:::`,
        sortOrder: 2,
      },
    ],
  })

  // Sections for l2
  await prisma.lessonSection.deleteMany({ where: { lessonId: l2.id } })
  await prisma.lessonSection.createMany({
    data: [
      {
        lessonId: l2.id,
        title: "What Is a Stall?",
        content: `A **stall** is an aerodynamic condition, not an airspeed condition. It occurs the moment the wing exceeds its **critical angle of attack** — typically around 15–18° depending on the airfoil.

At this point, smooth laminar airflow over the upper wing surface breaks down into **turbulent separated flow**. The wing can no longer generate enough lift to support the aircraft's weight.

Step through the four phases below to see exactly what happens to the airflow and lift at each stage — including recovery:

[DIAGRAM:stall-recovery]

:::warning
The #1 misconception: stalls happen when you "run out of airspeed." **Wrong.** You can stall at full throttle, in a dive, or in a steep turn at high speed. Angle of attack is the only factor that matters.
:::`,
        sortOrder: 1,
      },
      {
        lessonId: l2.id,
        title: "Stall Recovery",
        content: `The standard stall recovery procedure is three steps, executed simultaneously and promptly:

1. **Reduce angle of attack** — apply forward pressure on the yoke/stick to un-stall the wings
2. **Apply full power** — maximize thrust to minimize altitude loss
3. **Level the wings** — use coordinated rudder to stop any rolling tendency

:::tip
The FAA mnemonic is **"Pitch, Power, Rudder"** — in practice, all three happen nearly at the same moment.
:::

Altitude loss varies significantly by type of stall. A power-off stall at altitude may cost only 50–100 feet. An **accelerated stall** or **departure stall** (at high power, low altitude) can cost several hundred feet. Prompt recognition is everything.

:::warning
The most dangerous stalls occur during the **base-to-final turn** — a common scenario where the pilot over-banks and pulls back to avoid overshooting the runway. This can lead to a low-altitude, unrecoverable spin. Recognize the warning signs early.
:::`,
        sortOrder: 2,
      },
    ],
  })

  // Lessons for unit2
  const l3 = await prisma.lesson.upsert({
    where: { unitId_slug: { unitId: unit2.id, slug: "engines" } },
    update: {},
    create: { unitId: unit2.id, slug: "engines", title: "Reciprocating Engines", description: "How piston aircraft engines work.", estimatedMins: 10, sortOrder: 1 },
  })
  const l4 = await prisma.lesson.upsert({
    where: { unitId_slug: { unitId: unit2.id, slug: "fuel-systems" } },
    update: {},
    create: { unitId: unit2.id, slug: "fuel-systems", title: "Fuel Systems", description: "Fuel types, sumping, and fuel management.", estimatedMins: 8, sortOrder: 2 },
  })
  const l5 = await prisma.lesson.upsert({
    where: { unitId_slug: { unitId: unit2.id, slug: "electrical-systems" } },
    update: {},
    create: { unitId: unit2.id, slug: "electrical-systems", title: "Electrical Systems", description: "Battery, alternator, bus bar, and circuit protection.", estimatedMins: 12, sortOrder: 3 },
  })

  // Sections for l3
  await prisma.lessonSection.deleteMany({ where: { lessonId: l3.id } })
  await prisma.lessonSection.createMany({
    data: [
      {
        lessonId: l3.id,
        title: "The Four-Stroke Cycle",
        content: `Most training aircraft use a **horizontally-opposed, four-stroke, spark-ignition piston engine**. The engine produces power by burning a fuel/air mixture in cylinders. Each cylinder completes four distinct strokes per power cycle:

1. **Intake** — piston moves down, intake valve opens, fuel/air mixture is drawn in
2. **Compression** — both valves close, piston moves up, mixture compressed to ~1/8 volume
3. **Power** — spark plug fires, burning mixture expands and drives piston down — this is the only stroke that produces power
4. **Exhaust** — exhaust valve opens, piston moves up, burned gases pushed out

Step through the cycle using the interactive diagram:

[DIAGRAM:four-stroke]

:::info
Most training aircraft (like the Cessna 172) use a **four-cylinder, 160 hp Lycoming O-320** or similar. The firing order alternates cylinders to keep the crankshaft rotating smoothly.
:::`,
        sortOrder: 1,
      },
      {
        lessonId: l3.id,
        title: "Mixture Control",
        content: `The **mixture control** (red knob in most aircraft) adjusts the fuel/air ratio delivered to the engine.

At sea level, the fuel/air mixture is calibrated for maximum efficiency. As you climb, **air density decreases** but the fuel metering system delivers the same volume of fuel — making the mixture progressively **too rich** (excess fuel).

A rich mixture causes:
- Reduced engine efficiency
- Fouled spark plugs
- Increased fuel consumption

**Lean above 3,000 ft density altitude** to restore the correct ratio. The proper lean point is typically found by slowly pulling the mixture knob toward lean until engine RPM peaks, then enriching slightly.

:::warning
**Never lean below 75% power** or during takeoff and landing. A too-lean mixture at high power settings can cause engine damage from detonation.
:::`,
        sortOrder: 2,
      },
    ],
  })

  // Sections for l4
  await prisma.lessonSection.deleteMany({ where: { lessonId: l4.id } })
  await prisma.lessonSection.createMany({
    data: [
      {
        lessonId: l4.id,
        title: "Aviation Fuel Types",
        content: `General aviation aircraft use **aviation gasoline (Avgas)** — not automotive fuel. The grades are:

| Grade | Color | Use |
|-------|-------|-----|
| **100LL** | Blue | Most piston aircraft — "LL" = Low Lead |
| **100** (100/130) | Green | Older high-compression engines |
| **Jet-A** | Clear/straw | Turbine/jet engines only |

:::warning
**Misfueling is fatal.** Jet-A in a piston engine will cause engine failure. 100LL in a jet turbine will destroy it. Always verify fuel type before adding to the tanks.
:::

:::tip
The blue color of 100LL is a safety feature — it makes misfueling with Jet-A (clear) visually obvious during preflight.
:::`,
        sortOrder: 1,
      },
      {
        lessonId: l4.id,
        title: "Preflight Fuel Inspection",
        content: `Water contamination in aviation fuel is a leading cause of engine failure. Water is heavier than avgas and **sinks to the lowest point** in the tank and fuel system.

**Sumping procedure (required before every flight):**

1. Use the fuel sump tool (clear cylinder with a button valve)
2. Sample from each **wing tank sump**, the **gascolator/strainer**, and any other low points
3. Check for:
   - **Water** — appears as a separate clear layer at the bottom, or as bubbles
   - **Contamination** — dirt, debris, discoloration
   - **Correct color** — should be blue (100LL)
4. Discard contaminated samples away from the aircraft

:::info
If you find water, sump repeatedly until it's gone. Water often settles from condensation overnight — always sump after the aircraft has been parked for an extended period.
:::`,
        sortOrder: 2,
      },
    ],
  })

  // Sections for l5 (Electrical Systems)
  await prisma.lessonSection.deleteMany({ where: { lessonId: l5.id } })
  await prisma.lessonSection.createMany({
    data: [
      {
        lessonId: l5.id,
        title: "How the Electrical System Works",
        content: `Most training aircraft use a **12V or 24V direct-current (DC) electrical system**. Power flows from two sources — the battery and the alternator — through a master switch, to a central bus bar, and out through circuit breakers to individual systems.

Tap each component in the diagram to learn what it does:

[DIAGRAM:electrical-system]

:::info
The ACS (Airman Certification Standards) requires private pilot applicants to explain the electrical system, including the battery, alternator, master switch, and circuit protection devices. This is ACS Area of Operation I, Task G, Line Item F.
:::`,
        sortOrder: 1,
      },
      {
        lessonId: l5.id,
        title: "Circuit Protection & Alternator Failure",
        content: `**Circuit breakers (CBs)** protect each individual circuit from overload or short circuits. Unlike fuses, most aircraft circuit breakers are **resettable** — they pop out when tripped.

:::warning
A tripped circuit breaker may indicate a fault. FAA guidance: wait 1 minute, then reset **once**. If it trips again, leave it out — resetting a faulted circuit risks fire or further damage.
:::

When the alternator fails in flight, the battery becomes your only power source. The key skill is **load shedding** — systematically turning off non-essential equipment to stretch battery endurance.

Use the simulator below to practice. Click the red button to trigger a failure, then decide what to turn off:

[DIAGRAM:alternator-failure]

:::tip
Before any flight, know your aircraft's **total electrical load**. Add the amps of everything you plan to use. The alternator (60–70A output) minus your load is your safety margin. With the alternator out, that margin disappears instantly.
:::`,
        sortOrder: 2,
      },
    ],
  })

  // Questions for unit1 — always refresh
  await prisma.questionOption.deleteMany({ where: { question: { unitId: unit1.id } } })
  await prisma.question.deleteMany({ where: { unitId: unit1.id } })
  {
    const q1 = await prisma.question.create({ data: { unitId: unit1.id, question: "A stall occurs when:", explanation: "A stall always occurs at the critical angle of attack, regardless of airspeed or aircraft attitude. It is an aerodynamic condition, not an airspeed condition.", farAimRef: "FAA-H-8083-25B Ch.4", difficulty: "easy" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q1.id, text: "Airspeed drops below VS0", isCorrect: false, sortOrder: 1 },
      { questionId: q1.id, text: "The throttle is reduced to idle", isCorrect: false, sortOrder: 2 },
      { questionId: q1.id, text: "The wing exceeds its critical angle of attack", isCorrect: true, sortOrder: 3 },
      { questionId: q1.id, text: "The aircraft is in a nose-high attitude", isCorrect: false, sortOrder: 4 },
    ]})

    const q2 = await prisma.question.create({ data: { unitId: unit1.id, question: "In straight-and-level unaccelerated flight, which statement is true?", explanation: "In unaccelerated (constant velocity) flight, all four forces are in equilibrium: lift equals weight, and thrust equals drag.", farAimRef: "FAA-H-8083-25B Ch.4", difficulty: "easy" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q2.id, text: "Lift exceeds weight and thrust exceeds drag", isCorrect: false, sortOrder: 1 },
      { questionId: q2.id, text: "Thrust exceeds drag and lift equals weight", isCorrect: false, sortOrder: 2 },
      { questionId: q2.id, text: "Drag exceeds thrust and lift equals weight", isCorrect: false, sortOrder: 3 },
      { questionId: q2.id, text: "Lift equals weight and thrust equals drag", isCorrect: true, sortOrder: 4 },
    ]})

    const q3 = await prisma.question.create({ data: { unitId: unit1.id, question: "What is the correct stall recovery procedure?", explanation: "Stall recovery requires reducing angle of attack (forward pressure), applying full power, and leveling the wings with coordinated rudder to minimize altitude loss.", difficulty: "medium" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q3.id, text: "Apply back pressure and add power", isCorrect: false, sortOrder: 1 },
      { questionId: q3.id, text: "Reduce AoA, full power, level wings with rudder", isCorrect: true, sortOrder: 2 },
      { questionId: q3.id, text: "Reduce power and lower the nose sharply", isCorrect: false, sortOrder: 3 },
      { questionId: q3.id, text: "Apply aileron in the direction of the stall", isCorrect: false, sortOrder: 4 },
    ]})
  }

  // Questions for unit2 (fuel + electrical) — always refresh
  await prisma.questionOption.deleteMany({ where: { question: { unitId: unit2.id } } })
  await prisma.question.deleteMany({ where: { unitId: unit2.id } })
  {
    const q4 = await prisma.question.create({ data: { unitId: unit2.id, question: "Most training aircraft use which grade of aviation fuel?", explanation: "100LL (low-lead) avgas is the most common fuel for piston aircraft. It is dyed blue for easy identification.", difficulty: "easy" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q4.id, text: "80/87, dyed red", isCorrect: false, sortOrder: 1 },
      { questionId: q4.id, text: "Jet-A, dyed clear", isCorrect: false, sortOrder: 2 },
      { questionId: q4.id, text: "100LL (low-lead), dyed blue", isCorrect: true, sortOrder: 3 },
      { questionId: q4.id, text: "100LL, dyed green", isCorrect: false, sortOrder: 4 },
    ]})

    const q5 = await prisma.question.create({ data: { unitId: unit2.id, question: "Why should you lean the mixture at higher altitudes?", explanation: "As altitude increases, air density decreases, making the mixture too rich. Leaning restores the proper fuel/air ratio, improving engine efficiency and preventing fouled spark plugs.", difficulty: "medium" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q5.id, text: "Air density decreases, making the mixture too rich", isCorrect: true, sortOrder: 1 },
      { questionId: q5.id, text: "Fuel pressure increases at altitude", isCorrect: false, sortOrder: 2 },
      { questionId: q5.id, text: "The carburetor enriches automatically", isCorrect: false, sortOrder: 3 },
      { questionId: q5.id, text: "To reduce fuel flow for longer range only", isCorrect: false, sortOrder: 4 },
    ]})

    const q6 = await prisma.question.create({ data: { unitId: unit2.id, question: "During preflight, fuel sumped from the tanks appears clear with no bubbles. This indicates:", explanation: "Clear, bubble-free avgas is correct. Blue color confirms 100LL. Water contamination appears as a separate clear layer at the bottom or as bubbles.", difficulty: "easy" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q6.id, text: "Water contamination is present", isCorrect: false, sortOrder: 1 },
      { questionId: q6.id, text: "The fuel is 100LL and uncontaminated", isCorrect: true, sortOrder: 2 },
      { questionId: q6.id, text: "The fuel tank is empty", isCorrect: false, sortOrder: 3 },
      { questionId: q6.id, text: "Jet-A has been inadvertently added", isCorrect: false, sortOrder: 4 },
    ]})

    const q7 = await prisma.question.create({ data: { unitId: unit2.id, question: "The primary source of electrical power during flight is the:", explanation: "The alternator, driven by the engine, is the primary power source in flight. It powers all systems and charges the battery. The battery is a backup source used mainly for starting and emergency power.", farAimRef: "FAA-H-8083-25B Ch.7", difficulty: "easy" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q7.id, text: "Battery", isCorrect: false, sortOrder: 1 },
      { questionId: q7.id, text: "Voltage regulator", isCorrect: false, sortOrder: 2 },
      { questionId: q7.id, text: "Bus bar", isCorrect: false, sortOrder: 3 },
      { questionId: q7.id, text: "Alternator", isCorrect: true, sortOrder: 4 },
    ]})

    const q8 = await prisma.question.create({ data: { unitId: unit2.id, question: "If an alternator failure occurs in flight, the ammeter will show:", explanation: "When the alternator fails, it stops supplying current. The battery begins discharging to meet the electrical load, so the ammeter will show a discharge (negative) reading, indicating more current is being drawn than generated.", farAimRef: "FAA-H-8083-25B Ch.7", difficulty: "medium" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q8.id, text: "A high positive charge reading", isCorrect: false, sortOrder: 1 },
      { questionId: q8.id, text: "A discharge (negative or zero) reading", isCorrect: true, sortOrder: 2 },
      { questionId: q8.id, text: "No change — the battery compensates automatically", isCorrect: false, sortOrder: 3 },
      { questionId: q8.id, text: "A fluctuating reading as voltage regulator compensates", isCorrect: false, sortOrder: 4 },
    ]})

    const q9 = await prisma.question.create({ data: { unitId: unit2.id, question: "A circuit breaker trips in flight. After waiting 1 minute, you reset it and it trips again. You should:", explanation: "A circuit breaker that trips repeatedly indicates a fault in that circuit. FAA guidance states to reset a tripped CB only once. If it trips again, leave it out — resetting a faulted circuit risks fire or further electrical damage.", difficulty: "medium" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q9.id, text: "Reset it again immediately", isCorrect: false, sortOrder: 1 },
      { questionId: q9.id, text: "Turn off the master switch and reset all breakers", isCorrect: false, sortOrder: 2 },
      { questionId: q9.id, text: "Leave it out and assume there is a circuit fault", isCorrect: true, sortOrder: 3 },
      { questionId: q9.id, text: "Declare an emergency and land as soon as possible", isCorrect: false, sortOrder: 4 },
    ]})
  }

  // Unit 3: Performance Maneuvers (ACS Area V)
  const unit3 = await prisma.unit.upsert({
    where: { trackId_slug: { trackId: ppl.id, slug: "performance-maneuvers" } },
    update: {},
    create: { trackId: ppl.id, slug: "performance-maneuvers", title: "Performance Maneuvers", description: "Steep turns, slow flight, and performance takeoffs/landings.", icon: "🔄", sortOrder: 3 },
  })

  const l6 = await prisma.lesson.upsert({
    where: { unitId_slug: { unitId: unit3.id, slug: "steep-turns" } },
    update: {},
    create: { unitId: unit3.id, slug: "steep-turns", title: "Steep Turns", description: "ACS V-A: Maintaining coordinated flight at 45° bank.", estimatedMins: 12, sortOrder: 1 },
  })

  await prisma.lessonSection.deleteMany({ where: { lessonId: l6.id } })
  await prisma.lessonSection.createMany({
    data: [
      {
        lessonId: l6.id,
        title: "Why Bank Angle Matters",
        content: `In any banked turn, the total lift vector tilts with the wings. Only the **vertical component** of lift supports the aircraft's weight — the horizontal component is what makes the aircraft turn.

As bank angle increases:
- The vertical component of lift **decreases** (less lift fighting gravity)
- To maintain altitude, total lift must **increase** (more back pressure)
- **Load factor (G-force)** increases — the aircraft and pilot feel heavier
- **Stall speed increases** — the wing must work harder, so it reaches its critical AoA sooner

Use the slider below to explore the relationship between bank angle and these factors:

[DIAGRAM:steep-turn]

:::warning
At 60° of bank, the load factor is **2.0G** — the aircraft effectively weighs twice as much. Most normal-category GA aircraft are certified to **3.8G**. Beyond 60° bank, load factors climb rapidly toward that structural limit.
:::`,
        sortOrder: 1,
      },
      {
        lessonId: l6.id,
        title: "Flying the Steep Turn (ACS Standards)",
        content: `The private pilot ACS requires steep turns at **45° bank angle, ±5°**, with:

- Altitude: ±100 feet
- Airspeed: ±10 knots
- Bank: ±5° from 45°
- Heading: Roll out within ±10° of entry heading
- Complete at least one 360° turn in each direction

**Procedure:**

1. Clear the area — look for traffic
2. Note your heading and pick a reference point on the horizon
3. Establish cruise speed and altitude
4. Smoothly roll into a 45° bank
5. **Add back pressure** — this is the key; at 45° you need ~41% more lift
6. **Add a small amount of power** — the increased drag requires it to hold airspeed
7. **Trim is optional** — some instructors prefer you hold the pressure manually
8. Watch for the reference point — begin rollout ~20° before your heading
9. Reverse and repeat in the opposite direction

:::tip
The most common error is losing altitude in the first 90° of the turn. As soon as the bank reaches 45°, immediately apply additional back pressure — don't wait for the altimeter to unwind.
:::

:::info
**Overbanking tendency**: In a steep turn, the outside wing moves faster and produces more lift, which tends to steepen the bank. You may need slight opposite aileron to maintain exactly 45°.
:::`,
        sortOrder: 2,
      },
    ],
  })

  // Questions for unit3 (Performance Maneuvers) — always refresh
  await prisma.questionOption.deleteMany({ where: { question: { unitId: unit3.id } } })
  await prisma.question.deleteMany({ where: { unitId: unit3.id } })
  {
    const q10 = await prisma.question.create({ data: { unitId: unit3.id, question: "In a 45° banked turn, the load factor is approximately:", explanation: "Load factor = 1/cos(bank angle). At 45°, cos(45°) ≈ 0.707, so load factor = 1/0.707 ≈ 1.41G. The aircraft effectively weighs 41% more than in straight-and-level flight.", farAimRef: "FAA-H-8083-25B Ch.5", difficulty: "medium" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q10.id, text: "1.0G", isCorrect: false, sortOrder: 1 },
      { questionId: q10.id, text: "2.0G", isCorrect: false, sortOrder: 2 },
      { questionId: q10.id, text: "1.2G", isCorrect: false, sortOrder: 3 },
      { questionId: q10.id, text: "1.4G", isCorrect: true, sortOrder: 4 },
    ]})

    const q11 = await prisma.question.create({ data: { unitId: unit3.id, question: "At 60° of bank, the load factor is:", explanation: "Load factor = 1/cos(60°) = 1/0.5 = 2.0G. At this bank angle, the aircraft's apparent weight has doubled and the stall speed has increased by approximately 41%.", farAimRef: "FAA-H-8083-25B Ch.5", difficulty: "medium" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q11.id, text: "2.0G", isCorrect: true, sortOrder: 1 },
      { questionId: q11.id, text: "1.5G", isCorrect: false, sortOrder: 2 },
      { questionId: q11.id, text: "3.0G", isCorrect: false, sortOrder: 3 },
      { questionId: q11.id, text: "1.7G", isCorrect: false, sortOrder: 4 },
    ]})

    const q12 = await prisma.question.create({ data: { unitId: unit3.id, question: "During a steep turn, the pilot must add back pressure primarily because:", explanation: "When the aircraft banks, the total lift vector tilts. The vertical component of lift decreases. To maintain altitude, the total lift (and therefore the vertical component) must increase, which requires increased angle of attack — achieved by pulling back on the yoke.", farAimRef: "FAA-H-8083-25B Ch.5", difficulty: "medium" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q12.id, text: "The aircraft nose tends to pitch up automatically", isCorrect: false, sortOrder: 1 },
      { questionId: q12.id, text: "Back pressure prevents exceeding VNE", isCorrect: false, sortOrder: 2 },
      { questionId: q12.id, text: "The vertical component of lift decreases as bank increases", isCorrect: true, sortOrder: 3 },
      { questionId: q12.id, text: "The ailerons produce adverse yaw", isCorrect: false, sortOrder: 4 },
    ]})

    const q13 = await prisma.question.create({ data: { unitId: unit3.id, question: "The private pilot ACS steep turn standard requires:", explanation: "The ACS standard for steep turns is 45° of bank, maintaining altitude within ±100 feet, airspeed within ±10 knots, and rolling out within ±10° of the entry heading.", farAimRef: "FAA-S-ACS-6B V.A", difficulty: "easy" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q13.id, text: "60° bank, ±200 ft altitude, ±15 kts airspeed", isCorrect: false, sortOrder: 1 },
      { questionId: q13.id, text: "45° bank, ±100 ft altitude, ±10 kts airspeed", isCorrect: true, sortOrder: 2 },
      { questionId: q13.id, text: "30° bank, ±50 ft altitude, ±5 kts airspeed", isCorrect: false, sortOrder: 3 },
      { questionId: q13.id, text: "45° bank, ±200 ft altitude, ±20 kts airspeed", isCorrect: false, sortOrder: 4 },
    ]})
  }

  // Lesson 7: Ground Reference Maneuvers (ACS V-B)
  const l7 = await prisma.lesson.upsert({
    where: { unitId_slug: { unitId: unit3.id, slug: "ground-reference-maneuvers" } },
    update: {},
    create: { unitId: unit3.id, slug: "ground-reference-maneuvers", title: "Ground Reference Maneuvers", description: "ACS V-B: Turns around a point, S-turns, rectangular course.", estimatedMins: 14, sortOrder: 2 },
  })

  await prisma.lessonSection.deleteMany({ where: { lessonId: l7.id } })
  await prisma.lessonSection.createMany({
    data: [
      {
        lessonId: l7.id,
        title: "Turns Around a Point",
        content: `**Turns around a point** is the foundational ground reference maneuver. The pilot flies a constant-radius circle around a fixed ground reference point while maintaining a constant altitude.

The challenge: **wind**. Without wind, a constant bank angle produces a constant-radius circle. With wind, groundspeed continuously changes around the orbit. Since turn radius depends on groundspeed (faster = wider turn), the pilot must continuously vary bank angle to compensate:

- **Upwind side** (heading into wind) — lower groundspeed → **shallower bank**
- **Downwind side** (heading with wind) — higher groundspeed → **steeper bank**

The relationship is: tan(bank) ∝ groundspeed². Even a modest 15-knot wind produces a significant bank angle variation around the orbit.

[DIAGRAM:turns-around-point]

:::info
**ACS Standard (V-B):** Select a suitable ground reference point, enter at 600–1,000 ft AGL, maintain altitude ±100 ft, airspeed ±10 knots, bank ±5° of entry bank.
:::

:::tip
Pick a distinct, isolated ground reference point you can keep in sight throughout — an intersection, a tank, or a lone tree. Brief yourself on the wind direction before entry so you know which side needs more bank.
:::`,
        sortOrder: 1,
      },
      {
        lessonId: l7.id,
        title: "S-Turns & Rectangular Course",
        content: `### S-Turns Across a Road

The pilot flies a series of equal-radius semicircles on alternating sides of a straight ground reference line (typically a road or fence line). The entry is perpendicular to the line, wings level, then the pilot immediately begins a turn.

**Bank angle logic** — same principle as turns around a point:
- When the semicircle is on the **downwind side**, enter with a **steep bank** and gradually shallow as the turn progresses (groundspeed decreasing as you turn upwind)
- When the semicircle is on the **upwind side**, enter with a **shallow bank** and steepen toward the line (groundspeed increasing)

:::tip
A good way to set up: identify the wind direction, cross the road at 90°, and immediately establish your steepest bank on the downwind semicircle. If the arcs are unequal, reassess your entry bank.
:::

---

### Rectangular Course

The rectangular course simulates the airport traffic pattern. The pilot flies a rectangle around a field or section of land, maintaining a constant distance from each side.

| Leg | Wind Effect | Bank Correction |
|-----|------------|----------------|
| **Downwind** | Tailwind — drift away from field | Crab toward field |
| **Base** | Crosswind | Steeper bank on base-to-final (tailwind) |
| **Upwind** | Headwind — drift toward field | Crab away from field |
| **Crosswind** | Crosswind | Shallower bank on upwind turn |

:::warning
The rectangular course teaches the same skills as the traffic pattern. The base-to-final turn is where stall/spin accidents occur — do not let the aircraft drift inside the intended ground track and then pull back to compensate. Recognize the tendency early.
:::

:::info
All three ground reference maneuvers (turns around a point, S-turns, rectangular course) share the same underlying principle: **ground track control through continuous bank variation**. Master one and the others follow naturally.
:::`,
        sortOrder: 2,
      },
    ],
  })

  // Quiz questions for ground reference maneuvers (already deleted above with unit3)
  {
    const q14 = await prisma.question.create({ data: { unitId: unit3.id, question: "During turns around a point, why must the pilot use a steeper bank on the downwind side?", explanation: "On the downwind side of the orbit, the aircraft has a tailwind, increasing groundspeed. A higher groundspeed produces a wider turn radius at a given bank angle. To maintain the same radius, the pilot must increase bank angle on the downwind side.", farAimRef: "FAA-H-8083-3C Ch.6", difficulty: "medium" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q14.id, text: "The aircraft tends to pitch down in a tailwind", isCorrect: false, sortOrder: 1 },
      { questionId: q14.id, text: "Lift decreases in tailwind conditions", isCorrect: false, sortOrder: 2 },
      { questionId: q14.id, text: "ATC requires steeper banks when flying downwind", isCorrect: false, sortOrder: 3 },
      { questionId: q14.id, text: "Higher groundspeed requires more bank to maintain the radius", isCorrect: true, sortOrder: 4 },
    ]})

    const q15 = await prisma.question.create({ data: { unitId: unit3.id, question: "During S-turns across a road, where should the steepest bank occur?", explanation: "The steepest bank occurs immediately after crossing the road heading downwind. At that point groundspeed is highest (tailwind), so the most bank is required. As the aircraft turns into the wind, groundspeed decreases and bank is progressively reduced.", farAimRef: "FAA-H-8083-3C Ch.6", difficulty: "medium" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q15.id, text: "Immediately after crossing the road on the downwind side", isCorrect: true, sortOrder: 1 },
      { questionId: q15.id, text: "At the midpoint of each semicircle", isCorrect: false, sortOrder: 2 },
      { questionId: q15.id, text: "Immediately after crossing the road on the upwind side", isCorrect: false, sortOrder: 3 },
      { questionId: q15.id, text: "At the same point on both sides of the road", isCorrect: false, sortOrder: 4 },
    ]})

    const q16 = await prisma.question.create({ data: { unitId: unit3.id, question: "The rectangular course is most useful for teaching which practical skill?", explanation: "The rectangular course directly simulates the airport traffic pattern — flying legs at constant distance from a ground reference while compensating for wind with crab angles. It trains the judgment needed for every pattern at every airport.", farAimRef: "FAA-H-8083-3C Ch.6", difficulty: "easy" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q16.id, text: "Stall recovery at low altitude", isCorrect: false, sortOrder: 1 },
      { questionId: q16.id, text: "Instrument scan techniques", isCorrect: false, sortOrder: 2 },
      { questionId: q16.id, text: "Traffic pattern procedures and wind correction", isCorrect: true, sortOrder: 3 },
      { questionId: q16.id, text: "Engine failure procedures", isCorrect: false, sortOrder: 4 },
    ]})

    const q17 = await prisma.question.create({ data: { unitId: unit3.id, question: "What altitude is typically used for ground reference maneuvers?", explanation: "Ground reference maneuvers are conducted at 600–1,000 ft AGL — low enough to clearly reference the ground for track control, but high enough to allow recovery from errors. The ACS specifies this range.", farAimRef: "FAA-S-ACS-6B V.B", difficulty: "easy" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: q17.id, text: "1,500–2,000 ft AGL", isCorrect: false, sortOrder: 1 },
      { questionId: q17.id, text: "600–1,000 ft AGL", isCorrect: true, sortOrder: 2 },
      { questionId: q17.id, text: "300–500 ft AGL", isCorrect: false, sortOrder: 3 },
      { questionId: q17.id, text: "2,500 ft MSL", isCorrect: false, sortOrder: 4 },
    ]})
  }

  // Unit 4: Airspace & Regulations
  const unit4 = await prisma.unit.upsert({
    where: { trackId_slug: { trackId: ppl.id, slug: "airspace-regulations" } },
    update: {},
    create: { trackId: ppl.id, slug: "airspace-regulations", title: "Airspace & Regulations", description: "Airspace classification, VFR weather minimums, and flight rules.", icon: "🗺️", sortOrder: 4 },
  })

  const l8 = await prisma.lesson.upsert({
    where: { unitId_slug: { unitId: unit4.id, slug: "airspace-classification" } },
    update: {},
    create: { unitId: unit4.id, slug: "airspace-classification", title: "Airspace Classification", description: "Classes A through G — entry requirements, equipment, and weather minimums.", estimatedMins: 15, sortOrder: 1 },
  })

  await prisma.lessonSection.deleteMany({ where: { lessonId: l8.id } })
  await prisma.lessonSection.createMany({
    data: [
      {
        lessonId: l8.id,
        title: "The Six Classes of Airspace",
        content: `US airspace is divided into six classes — A, B, C, D, E, and G. Each class has different rules for entry, equipment, and weather.

The simplest way to think about them: **controlled vs. uncontrolled**, and **how busy is the airport below?**

- **Class A** — the high-altitude enroute structure above FL180. Always IFR, always a clearance.
- **Class B** — the "bowl" around the busiest airports. Explicit clearance required.
- **Class C** — two-ring magenta circles around medium airports. Radio contact required.
- **Class D** — blue dashed circle around towered airports. Radio contact required.
- **Class E** — all other controlled airspace (fills in the gaps). No clearance for VFR.
- **Class G** — uncontrolled surface airspace below Class E. No requirements.

Tap each class in the diagram to see its exact altitude limits, entry rules, equipment requirements, and VFR weather minimums:

[DIAGRAM:airspace]

:::warning
The most commonly failed written exam topic is airspace. Know the difference between **Class B entry** (explicit clearance: "Cleared into Class Bravo") and **Class C/D entry** (two-way communication established — ATC acknowledging your call sign is sufficient, even if they say "standby").
:::`,
        sortOrder: 1,
      },
      {
        lessonId: l8.id,
        title: "VFR Weather Minimums",
        content: `VFR weather minimums exist to ensure you can see and avoid traffic. They get more restrictive at night and in controlled airspace.

### The Simple Rule for Class B, C, D, and E (below 10,000 ft)
**3 SM visibility · 500 ft below / 1,000 ft above / 2,000 ft horizontal from clouds**

### The Exception: Class G Below 1,200 AGL (Day Only)
**1 SM visibility · Clear of clouds** — the most permissive standard in the system.

### Above 10,000 ft MSL (all classes)
**5 SM visibility · 1,000 ft below / 1,000 ft above / 1 SM horizontal from clouds**

:::tip
The memory aid for B/C/D/E cloud clearance: **"152"** — 500 below (round to "1" thousand), 1,000 above, 2,000 horizontal. Or: "Below one, above one, two on the sides."
:::

:::warning
**Special VFR** allows you to operate in Class B, C, D, or E surface areas with less than standard VFR weather, but you need ATC clearance, visibility of at least 1 SM, and the ability to remain clear of clouds. At night, an instrument rating is required for Special VFR.
:::

| Airspace | Visibility | Cloud Clearance |
|----------|-----------|-----------------|
| Class A | N/A (IFR only) | N/A |
| Class B | 3 SM | Clear of clouds |
| Class C & D | 3 SM | 500 below, 1,000 above, 2,000 horiz |
| Class E (< 10k) | 3 SM | 500 below, 1,000 above, 2,000 horiz |
| Class E (≥ 10k) | 5 SM | 1,000 below, 1,000 above, 1 SM horiz |
| Class G (< 1,200 AGL, day) | 1 SM | Clear of clouds |
| Class G (< 1,200 AGL, night) | 3 SM | 500 below, 1,000 above, 2,000 horiz |`,
        sortOrder: 2,
      },
    ],
  })

  // Quiz questions for unit4 — always refresh
  await prisma.questionOption.deleteMany({ where: { question: { unitId: unit4.id } } })
  await prisma.question.deleteMany({ where: { unitId: unit4.id } })
  {
    const qa = await prisma.question.create({ data: { unitId: unit4.id, question: "To enter Class B airspace, a pilot must:", explanation: "Class B requires an explicit ATC clearance — the pilot must hear the words 'Cleared into Class Bravo.' Simply establishing radio contact or receiving a squawk code is not sufficient.", farAimRef: "14 CFR 91.131", difficulty: "easy" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: qa.id, text: "Establish two-way radio communication", isCorrect: false, sortOrder: 1 },
      { questionId: qa.id, text: "File a VFR flight plan", isCorrect: false, sortOrder: 2 },
      { questionId: qa.id, text: "Have an instrument rating", isCorrect: false, sortOrder: 3 },
      { questionId: qa.id, text: "Receive an explicit ATC clearance", isCorrect: true, sortOrder: 4 },
    ]})

    const qb = await prisma.question.create({ data: { unitId: unit4.id, question: "Approaching a Class D airport, ATC responds 'N12345, standby.' The pilot:", explanation: "In Class C and D airspace, entry requires two-way radio communication — ATC must acknowledge your call sign. 'Standby' with your call sign counts as communication. The pilot may enter and continue to communicate. Only a flat 'unable' or no response means you cannot enter.", farAimRef: "14 CFR 91.129", difficulty: "medium" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: qb.id, text: "May enter — two-way communication is established", isCorrect: true, sortOrder: 1 },
      { questionId: qb.id, text: "Must hold outside until ATC provides explicit clearance", isCorrect: false, sortOrder: 2 },
      { questionId: qb.id, text: "Must squawk 7600 (lost communications)", isCorrect: false, sortOrder: 3 },
      { questionId: qb.id, text: "May enter only if weather is above VFR minimums", isCorrect: false, sortOrder: 4 },
    ]})

    const qc = await prisma.question.create({ data: { unitId: unit4.id, question: "The VFR weather minimums in Class G airspace below 1,200 ft AGL during the day are:", explanation: "Class G airspace below 1,200 AGL during the day has the most permissive VFR minimums: 1 SM visibility and clear of clouds. At night, the minimums increase to 3 SM and standard cloud clearances.", farAimRef: "14 CFR 91.155", difficulty: "medium" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: qc.id, text: "3 SM visibility, 500/1,000/2,000 cloud clearance", isCorrect: false, sortOrder: 1 },
      { questionId: qc.id, text: "3 SM visibility, clear of clouds", isCorrect: false, sortOrder: 2 },
      { questionId: qc.id, text: "1 SM visibility, clear of clouds", isCorrect: true, sortOrder: 3 },
      { questionId: qc.id, text: "5 SM visibility, 1,000/1,000/1 SM cloud clearance", isCorrect: false, sortOrder: 4 },
    ]})

    const qd = await prisma.question.create({ data: { unitId: unit4.id, question: "Class E airspace typically begins at what altitude in a transition area near an airport?", explanation: "Transition areas (shown as a magenta vignette on sectional charts) have a Class E floor of 700 ft AGL. This lower floor protects IFR aircraft on instrument approaches from uncontrolled Class G traffic below. Away from airports, Class E generally starts at 1,200 AGL.", farAimRef: "FAA-H-8083-25B Ch.15", difficulty: "medium" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: qd.id, text: "1,200 ft AGL", isCorrect: false, sortOrder: 1 },
      { questionId: qd.id, text: "700 ft AGL", isCorrect: true, sortOrder: 2 },
      { questionId: qd.id, text: "2,500 ft AGL", isCorrect: false, sortOrder: 3 },
      { questionId: qd.id, text: "FL180", isCorrect: false, sortOrder: 4 },
    ]})
  }

  // Unit 5: Aviation Weather
  const unit5 = await prisma.unit.upsert({
    where: { trackId_slug: { trackId: ppl.id, slug: "aviation-weather" } },
    update: {},
    create: { trackId: ppl.id, slug: "aviation-weather", title: "Aviation Weather", description: "Hazards, forecasts, and the weather products every pilot must understand.", icon: "🌦️", sortOrder: 5 },
  })

  const l9 = await prisma.lesson.upsert({
    where: { unitId_slug: { unitId: unit5.id, slug: "weather-hazards" } },
    update: {},
    create: { unitId: unit5.id, slug: "weather-hazards", title: "Weather Hazards", description: "Thunderstorms, icing, turbulence, wind shear, and density altitude.", estimatedMins: 15, sortOrder: 1 },
  })

  await prisma.lessonSection.deleteMany({ where: { lessonId: l9.id } })
  await prisma.lessonSection.createMany({
    data: [
      {
        lessonId: l9.id,
        title: "Thunderstorms & Structural Icing",
        content: `### Thunderstorms

A thunderstorm requires three ingredients: **moisture**, **a lifting mechanism**, and **atmospheric instability**. All three must be present simultaneously. When they are, the result is one of the most hazardous environments a VFR pilot can encounter.

**The three stages:**

| Stage | Characteristics | Duration |
|-------|----------------|----------|
| **Cumulus** | Strong updrafts only, building vertically | 10–15 min |
| **Mature** | Both updrafts AND downdrafts, heaviest precipitation, most dangerous | 10–30 min |
| **Dissipating** | Downdrafts dominate, anvil top, rain decreasing | 15–30 min |

The **mature stage** is the most hazardous. It contains:
- Severe turbulence (updrafts/downdrafts exceeding 6,000 ft/min)
- Large hail — often extending miles beyond the visible cell
- Lightning — can strike aircraft well outside the cloud
- **Microburst** — a sudden, intense downdraft that spreads outward at ground level, causing severe wind shear

:::warning
The FAA's guidance is clear: **avoid thunderstorms by at least 20 nautical miles**. Do not attempt to fly under, over, or through a thunderstorm. Radar shows precipitation, not turbulence — severe turbulence can exist in clear air adjacent to a cell.
:::

---

### Structural Icing

Structural icing occurs when an aircraft flies through **supercooled liquid water droplets** — water that remains liquid below 0°C. On contact with the airframe, these droplets freeze instantly.

**Types of ice:**

| Type | Appearance | Hazard Level |
|------|-----------|-------------|
| **Clear (glaze)** | Transparent, smooth, heavy | Most dangerous — hard to see, heavy |
| **Rime** | White, rough, milky | Moderate — distorts airfoil shape |
| **Mixed** | Combination | High — worst properties of both |

Ice is dangerous because it:
1. **Destroys the airfoil shape** — even ¼ inch of ice on the leading edge can reduce lift by 25% and increase drag by 50%
2. **Adds weight** — 1 inch of clear ice over a typical GA wing weighs hundreds of pounds
3. **Affects control surfaces** — can jam or stiffen ailerons, elevator, and rudder

:::warning
Most single-engine GA aircraft (Cessna 172, Piper Cherokee, etc.) are **NOT certified for flight into known icing (FIKI)**. If you encounter unexpected icing, exit immediately — turn toward warmer air, descend to a lower altitude, or reverse course.
:::

:::tip
**Forecast tools:** Check AIRMETs (Airmen's Meteorological Information) for icing before every flight. AIRMET Sierra covers IFR conditions and mountain obscuration; **AIRMET Zulu covers icing**; AIRMET Tango covers turbulence. SIGMETs cover severe conditions.
:::`,
        sortOrder: 1,
      },
      {
        lessonId: l9.id,
        title: "Turbulence, Wind Shear & Density Altitude",
        content: `### Turbulence

Turbulence is classified by intensity:

| Intensity | Effect on Aircraft | Effect on Occupants |
|-----------|-------------------|---------------------|
| **Light** | Slight, erratic changes in altitude/attitude | Minor strain against seatbelts |
| **Moderate** | Similar but more intense — aircraft remains in control | Difficult to walk, food/drinks spill |
| **Severe** | Large, abrupt changes — momentarily out of control | Occupants thrown violently |
| **Extreme** | Aircraft impossible to control — structural damage possible | Rare; avoid at all costs |

**Sources of turbulence:**
- **Mechanical** — air flowing over uneven terrain, buildings, or trees
- **Thermal** — rising columns of warm air on hot days (especially over dark surfaces)
- **Wind shear** — rapid change in wind speed or direction over a short distance
- **Mountain wave** — standing waves downwind of ridgelines, can extend to the stratosphere
- **Clear Air Turbulence (CAT)** — high-altitude turbulence with no visual warning

:::tip
Turbulence encounters are best handled by slowing to **maneuvering speed (VA)**. At or below VA, the aircraft will stall before exceeding its structural limits. VA decreases with decreasing weight — check your POH for the correct value.
:::

---

### Wind Shear

Wind shear is a **sudden change in wind velocity or direction** over a short distance. It is most hazardous during approach and departure at low altitude, where airspeed and altitude margins are smallest.

**Low-Level Wind Shear (LLWS)** near airports can be caused by:
- Microburst (thunderstorm downdraft)
- Frontal passage
- Temperature inversions at low altitudes

The classic microburst encounter on approach:
1. Headwind increases → airspeed increases, aircraft climbs above glidepath
2. Pilot reduces power to correct
3. Downdraft begins → rapid loss of lift
4. Tailwind follows → airspeed drops sharply
5. Aircraft now below glidepath with insufficient power to recover

:::warning
**Microburst rule:** If you observe a microburst on or near the runway, do not attempt the approach. Wait at least 20 minutes — microbursts are short-lived but extremely intense (up to 6,000 ft/min downdraft, 45-knot wind shear).
:::

---

### Density Altitude

Density altitude is **pressure altitude corrected for non-standard temperature**. It represents the altitude the aircraft "thinks" it's at — the altitude at which its performance will match the POH.

**High density altitude = poor performance:**
- Engine produces less power (less air = less oxygen)
- Propeller produces less thrust (less air to bite)
- Wings produce less lift (less air over the airfoil)
- **Longer takeoff roll, reduced climb rate, longer landing distance**

:::warning
**High DA accidents are common at mountain airports in summer.** Leadville, CO (KLXV) sits at 9,927 ft MSL. On a hot summer day, density altitude can exceed 12,000 ft — the aircraft performs as if at 12,000 ft even while sitting on the ground. Always calculate density altitude before flight at high-elevation airports or on hot days.
:::

:::tip
**Rule of thumb:** Density altitude increases approximately **120 ft for every 1°C above standard temperature**. Standard temperature decreases 2°C per 1,000 ft of altitude. Use your E6B or a DA calculator before high-elevation or hot-day departures.
:::`,
        sortOrder: 2,
      },
    ],
  })

  // Quiz questions for unit5 — always refresh
  await prisma.questionOption.deleteMany({ where: { question: { unitId: unit5.id } } })
  await prisma.question.deleteMany({ where: { unitId: unit5.id } })
  {
    const qw1 = await prisma.question.create({ data: { unitId: unit5.id, question: "The most hazardous stage of a thunderstorm is the:", explanation: "The mature stage is the most dangerous. It contains both strong updrafts and downdrafts simultaneously, the heaviest precipitation, largest hail, most severe turbulence, and the greatest lightning activity.", farAimRef: "FAA-H-8083-28 Ch.11", difficulty: "easy" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: qw1.id, text: "Cumulus stage", isCorrect: false, sortOrder: 1 },
      { questionId: qw1.id, text: "Dissipating stage", isCorrect: false, sortOrder: 2 },
      { questionId: qw1.id, text: "Anvil stage", isCorrect: false, sortOrder: 3 },
      { questionId: qw1.id, text: "Mature stage", isCorrect: true, sortOrder: 4 },
    ]})

    const qw2 = await prisma.question.create({ data: { unitId: unit5.id, question: "Which type of structural ice is considered most dangerous?", explanation: "Clear (glaze) ice is the most dangerous. It is transparent and difficult to see, forms a heavy dense layer that closely conforms to the airfoil, and is hard to remove. It adds significant weight and degrades lift more severely than rime ice.", farAimRef: "FAA-H-8083-28 Ch.10", difficulty: "medium" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: qw2.id, text: "Clear (glaze) ice", isCorrect: true, sortOrder: 1 },
      { questionId: qw2.id, text: "Rime ice", isCorrect: false, sortOrder: 2 },
      { questionId: qw2.id, text: "Frost", isCorrect: false, sortOrder: 3 },
      { questionId: qw2.id, text: "Mixed ice", isCorrect: false, sortOrder: 4 },
    ]})

    const qw3 = await prisma.question.create({ data: { unitId: unit5.id, question: "An aircraft should slow to maneuvering speed (VA) in turbulence because:", explanation: "At or below maneuvering speed, the aircraft will aerodynamically stall before the airframe exceeds its design load limit. Above VA, a single full control deflection or a severe gust could overstress the structure.", farAimRef: "FAA-H-8083-25B Ch.5", difficulty: "medium" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: qw3.id, text: "Lower speed reduces turbulence intensity", isCorrect: false, sortOrder: 1 },
      { questionId: qw3.id, text: "VA gives the best glide ratio in rough air", isCorrect: false, sortOrder: 2 },
      { questionId: qw3.id, text: "The aircraft will stall before exceeding structural load limits", isCorrect: true, sortOrder: 3 },
      { questionId: qw3.id, text: "Slower speed improves pilot reaction time", isCorrect: false, sortOrder: 4 },
    ]})

    const qw4 = await prisma.question.create({ data: { unitId: unit5.id, question: "High density altitude affects aircraft performance by:", explanation: "High density altitude means thinner air. The engine ingests less oxygen (reducing power), the propeller has less air to accelerate (reducing thrust), and the wings generate less lift — all resulting in degraded takeoff, climb, and cruise performance.", farAimRef: "FAA-H-8083-25B Ch.11", difficulty: "easy" } })
    await prisma.questionOption.createMany({ data: [
      { questionId: qw4.id, text: "Increasing stall speed and improving climb rate", isCorrect: false, sortOrder: 1 },
      { questionId: qw4.id, text: "Reducing engine power, propeller thrust, and lift", isCorrect: true, sortOrder: 2 },
      { questionId: qw4.id, text: "Reducing drag and shortening the takeoff roll", isCorrect: false, sortOrder: 3 },
      { questionId: qw4.id, text: "Only affecting turbine engines, not piston aircraft", isCorrect: false, sortOrder: 4 },
    ]})
  }

  // Achievements
  const achievements = [
    { slug: "first-lesson", name: "First Flight", description: "Complete your first lesson.", icon: "🎯", xpReward: 50, category: "milestones" },
    { slug: "perfect-quiz", name: "Ace Pilot", description: "Score 100% on any quiz.", icon: "💯", xpReward: 100, category: "quizzes" },
    { slug: "7-day-streak", name: "Week Warrior", description: "Maintain a 7-day study streak.", icon: "🔥", xpReward: 75, category: "streaks" },
    { slug: "gold-mastery", name: "Gold Standard", description: "Earn gold mastery on a unit quiz.", icon: "🥇", xpReward: 150, category: "quizzes" },
    { slug: "ppl-complete", name: "Private Pilot", description: "Complete the entire PPL track.", icon: "🎓", xpReward: 500, category: "certifications" },
  ]
  for (const a of achievements) {
    await prisma.achievement.upsert({ where: { slug: a.slug }, update: {}, create: a })
  }

  console.log("Seed complete.")
}

main().catch(console.error).finally(() => prisma.$disconnect())
